jenkins:
  systemMessage: "🚀 Ephemeral Jenkins configured via JCasC"
  # ✅ FIX: This line solves the "Built-in node" security warning
  numExecutors: 0
  mode: NORMAL
  
  # 1. Global Environment Variables
  globalNodeProperties:
    - envVars:
        env:
          - key: "PROJECT_ID"
            value: "${PROJECT_ID}"
  
  # 2. Clouds (Kubernetes Agent Configuration)
  clouds:
    - kubernetes:
        name: "kubernetes"
        serverUrl: "https://kubernetes.default.svc"
        skipTlsVerify: true
        namespace: "jenkins"
        # ✅ VERIFIED: Correct Internal DNS (Port 80)
        jenkinsUrl: "http://jenkins-service.jenkins.svc.cluster.local"
        jenkinsTunnel: "jenkins-service.jenkins.svc.cluster.local:50000"
        containerCapStr: "10"
        podRetention: "never"
        templates:
          - name: "default-agent"
            label: "standard"
            nodeUsageMode: "NORMAL"
            containers:
              - name: "jnlp"
                # Recommended: Pin this to a specific version if 'latest' breaks
                image: "jenkins/inbound-agent:latest" 
                resourceRequestCpu: "250m"   # Optimized for Spot instances
                resourceRequestMemory: "256Mi"
                resourceLimitCpu: "1"
                resourceLimitMemory: "1Gi"

# 3. Credentials
credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "github-access-token"
              username: "${GITHUB_USER}"
              password: "${GITHUB_TOKEN}"
              description: "GitHub Token (Auto-injected)"

# 4. Security
security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false

# 5. Pre-configured Jobs
jobs:
  - script: >
      pipelineJob('BigQuery-Demo') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/${GITHUB_USER}/jenpy.git')
                  credentials('github-access-token')
                }
                branch('*/main')
              }
            }
            scriptPath('pipelines/demo-pipeline.jenkinsfile')
          }
        }
      }