jenkins:
  systemMessage: "🚀 Ephemeral Jenkins configured via JCasC"
  numExecutors: 0
  mode: NORMAL
  
  globalNodeProperties:
    - envVars:
        env:
          - key: "PROJECT_ID"
            value: "${PROJECT_ID}"
  
  clouds:
    - kubernetes:
        name: "kubernetes"
        serverUrl: "https://kubernetes.default.svc"
        skipTlsVerify: true
        namespace: "jenkins"
        jenkinsUrl: "http://jenkins-service.jenkins.svc.cluster.local"
        jenkinsTunnel: "jenkins-service.jenkins.svc.cluster.local:50000"
        containerCapStr: "10"
        podRetention: "never"
        templates:
          - name: "default-agent"
            label: "standard"
            nodeUsageMode: "NORMAL"
            containers:
              - name: "jnlp"
                image: "jenkins/inbound-agent:latest" 
                resourceRequestCpu: "250m"
                resourceRequestMemory: "256Mi"
                resourceLimitCpu: "1"
                resourceLimitMemory: "1Gi"

credentials:
  system:
    domainCredentials:
      - credentials:
          - usernamePassword:
              scope: GLOBAL
              id: "github-access-token"
              username: "${GITHUB_USER}"
              password: "${GITHUB_TOKEN}"
              description: "GitHub Token (Auto-injected)"

security:
  globalJobDslSecurityConfiguration:
    useScriptSecurity: false

jobs:
  - script: >
      pipelineJob('BigQuery-Demo') {
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/${GITHUB_USER}/jenpy.git')
                  credentials('github-access-token')
                }
                branch('*/main')
              }
            }
            scriptPath('pipelines/demo-pipeline.jenkinsfile')
          }
        }
      }

  - script: >
      pipelineJob('Create-Table-Tool') {
        description('Utility job to create BigQuery tables using a defined JSON schema.')
        definition {
          cpsScm {
            scm {
              git {
                remote {
                  url('https://github.com/${GITHUB_USER}/jenpy.git')
                  credentials('github-access-token')
                }
                branch('*/main')
              }
            }
            scriptPath('pipelines/create-table.jenkinsfile')
          }
        }
      }

  - script: >
      multibranchPipelineJob('Pull-Request-CI') {
        description('Automatically checks PRs and Branches')
          branchSources {
            branchSource {
                source {
                    github {
                        id('github-source')
                        credentialsId('github-access-token')
                        repoOwner('${GITHUB_USER}')
                        repository('jenpy')
                        traits {
                            gitHubBranchDiscovery {
                                strategyId(1) // 1 = Exclude branches that are also filed as PRs
                            }
                            gitHubPullRequestDiscovery {
                                strategyId(1) // 1 = Merge PR with target branch (Test the merge)
                            }
                        }
                    }
                }
            }
        }